try:
    result = 45/0

except:
    print('error happended')

finally:
    print('finally here')
print('done')